### ISSUE TITLE
Module 'jet' not found

### ISSUE THREAD

**Issue by Pilgrim1379** [kdheepak/JET.nvim#1]
I'm using neovim version `0.8.0` with packer for package management. I followed the instructions to install and configure JET.vim. However when I start neovim I get the following error message:

```

Error detected while processing /Users/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/user/.config/nvim/lua/plugins/nvim-lspconfi
g.lua:76: module 'jet' not found:
        no field package.preload['jet']
        no file './jet.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-bet
a3/jet.lua'
        no file '/usr/local/share/lua/5.1/jet.lua'
        no file '/usr/local/share/lua/5.1/jet/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/jet.lua'

        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/jet/init
.lua'
        no file './jet.so'
        no file '/usr/local/lib/lua/5.1/jet.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/jet.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/nqa/.config/nvim/lua/plugins/nvim-lspconfig.lua:76: in main chunk
        [C]: in function 'require'
        /Users/nqa/.config/nvim/init.lua:16: in main chunk
```
 The following are my current related config in `packer.startup`:

```
use({
  "kdheepak/JET.nvim",
  requires = "jose-elias-alvarez/null-ls.nvim",
  run = [[mkdir -p ~/.julia/environments/nvim-null-ls && julia --startup-file=no --project=~/.julia/environments/nvim-null-ls -e 'using Pkg; Pkg.add("JET")']],
  ft = { "julia" },
  config = function()
    require("jet").setup()
  end,
})
```

That's all the config I've got related to JET.vim. I also use `null-ls` however I don't have any JET.vim related config in there.

Thanks.

**Comment by kdheepak** [comment]
I'm not sure why it says that error for you. The file exists in the repo: https://github.com/kdheepak/JET.nvim/blob/main/lua/jet.lua

Can you try `PackerCompile`, `PackerClean` and restart neovim?

**Comment by kdheepak** [comment]
Also try removing this line from your packer use function:

```
  ft = { "julia" },
```

For this plugin. Just based on the error message, I think you are trying to `require("jet")` for null-ls but because you have the filetype set, packer will only lazy load the plugin when you open a Julia file, and that might be causing the error.

**Comment by Pilgrim1379** [comment]
Thanks for the swift response. I did what you suggested and unfortunately, the error persists. I however saw this after neovin has started:

```
packer.nvim: Error running config for JET.nvim: ...cal/share/nvim/site/pack/packer/opt/
JET.nvim/lua/jet.lua:46: attempt to call field 'config' (a nil value)
```
Don't know if it helps?

**Comment by kdheepak** [comment]
It looks like I haven't updated this package to work with the more recent versions of null ls. Let me take a look into that and I'll post here when I have an update.

**Comment by Pilgrim1379** [comment]
Thanks

**Comment by josephsdavid** [comment]
This should be fixed!
